[server]
enableStaticServing = true

[[theme.fontFaces]]
family = "SpaceGrotesk"
url = "app/static/SpaceGrotesk-VariableFont_wght.ttf"

[[theme.fontFaces]]
family = "SpaceGroteskHeader"
url = "app/static/SpaceGrotesk-SemiBold.ttf"

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-Bold.ttf"
style = "normal"
weight = 700

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-BoldItalic.ttf"
style = "italic"
weight = 700

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-Italic.ttf"
style = "italic"
weight = 400

[[theme.fontFaces]]
family = "SpaceMono"
url = "app/static/SpaceMono-Regular.ttf"
style = "normal"
weight = 400

[theme]
base="light"
baseFontSize = 12
primaryColor = "#0c53fb"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f2f5fa"
textColor = "#19233b"
linkColor = "#0c53fb"
showSidebarBorder = false
borderColor = "#dddfe9"
showWidgetBorder = true
baseRadius = "0.8rem"
font = "SpaceGrotesk"
headingFont = "SpaceGroteskHeader"


[theme.sidebar]
backgroundColor = "#f1f5fb"
secondaryBackgroundColor = "#ffffff"